/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Candis-S31 low-power framework prototype.
 *
 * Four power states, walked in a loop so the whole machine is exercised:
 *
 *   S0 RUN        display on, LP housekeeper polls the shared IRQ line while
 *                 the HP core light-sleeps between mailbox reports.
 *   S1 SCREEN_OFF CO5300 in sleep, CST820 in monitor mode, HP in light sleep.
 *                 Wake sources: touch INT, shared IRQ line, RTC timer.
 *   DEEP_SLEEP    SoC deep sleep entered on S1 timeout, woken by the SoC RTC
 *                 timer or the shared IRQ line (EXT1 on GPIO2). Waking is a
 *                 reboot; a cycle counter kept in RTC memory decides whether
 *                 the machine gets another S0 pass or escalates to S2.
 *   S2 SHUTDOWN   peripheral rails off, RX8130CE alarm armed, then the PMIC
 *                 performs a software power-off (bsp_pmic_power_off()). The
 *                 ESP loses power, so the "wake" from S2 is a cold boot after
 *                 the PMIC powers the board again.
 *
 * Deep sleep works on ESP32-S31: both the plain timer wake-up and EXT1 on a
 * pulled pin wake the chip reliably. Earlier revisions of this file claimed
 * otherwise because the EXT1 pin under test was left floating. The one hard
 * requirement is a defined level on every EXT1 wake pin: a floating pad keeps
 * the chip in deep sleep forever. GPIO2 is pulled up through R10 on this
 * board, so it is safe to use as the EXT1 source here. See the README.
 */

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "esp_attr.h"
#include "esp_bit_defs.h"
#include "esp_check.h"
#include "esp_err.h"
#include "esp_log.h"
#include "esp_sleep.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"

#include "driver/gpio.h"
#include "driver/rtc_io.h"

#include "bsp/esp-bsp.h"
#include "esp_lcd_touch_cst820.h"
#include "rx8130ce.h"

#include "lp_core_mailbox.h"
#include "ulp_lp_core.h"

#include "lp_shared.h"

/* Generated by ulp_embed_binary() from main/lp_core/main.c. It exports the
 * ulp_* symbols; the embedded binary bounds are linker symbols and have to be
 * declared by hand, as in the IDF lp_core mailbox example. */
#include "lp_core_main.h"

extern const uint8_t lp_core_main_bin_start[] asm("_binary_lp_core_main_bin_start");
extern const uint8_t lp_core_main_bin_end[] asm("_binary_lp_core_main_bin_end");

/** Seconds spent in S0 before dropping to S1. */
#define S0_DWELL_SECONDS        15
/** Light-sleep slice used inside S0 while waiting for LP reports. */
#define S0_SLEEP_SLICE_US       (2 * 1000 * 1000ULL)
/** Light-sleep slice used inside S1 (RTC-timer wake source). */
#define S1_SLEEP_SLICE_US       (10 * 1000 * 1000ULL)
/** Number of S1 light-sleep slices before escalating to S2. */
#define S1_SLICES_BEFORE_S2     3
/** Minutes from now to the RX8130CE alarm armed in S2. */
#define S2_ALARM_MINUTES        5
/** Depth of the queue draining LP mailbox reports into the state machine. */
#define LP_REPORT_QUEUE_DEPTH   16
/** SoC RTC timer period used as a deep-sleep wake source. */
#define DEEP_SLEEP_WAKE_US      (20 * 1000 * 1000ULL)
/** Number of deep-sleep passes before the machine escalates to S2. */
#define DEEP_SLEEP_MAX_CYCLES   2
/** Magic guarding the RTC-memory deep-sleep counter against power-on garbage. */
#define DEEP_SLEEP_COUNT_MAGIC  0xDEE5C311U

static const char *TAG = "candis_lp";

/** Power states of the prototype. */
typedef enum {
    CANDIS_STATE_RUN = 0,       /**< S0: full operation, LP core delegated. */
    CANDIS_STATE_SCREEN_OFF,    /**< S1: panel asleep, HP in light sleep. */
    CANDIS_STATE_DEEP_SLEEP,    /**< SoC deep sleep between S1 and S2. */
    CANDIS_STATE_SHUTDOWN,      /**< S2: rails down, RTC alarm armed. */
    CANDIS_STATE_COUNT,
} candis_state_t;

static const char *const s_state_names[CANDIS_STATE_COUNT] = {
    [CANDIS_STATE_RUN] = "S0-RUN",
    [CANDIS_STATE_SCREEN_OFF] = "S1-SCREEN_OFF",
    [CANDIS_STATE_DEEP_SLEEP] = "DEEP_SLEEP",
    [CANDIS_STATE_SHUTDOWN] = "S2-SHUTDOWN",
};

static lp_mailbox_t s_mailbox;
static bool s_lp_running;
static esp_lcd_touch_handle_t s_touch;
static esp_lcd_panel_handle_t s_panel;
static esp_lcd_panel_io_handle_t s_panel_io;
static bool s_display_ready;
static bool s_display_asleep;
static QueueHandle_t s_lp_reports;

static const char *state_name(candis_state_t state)
{
    return state < CANDIS_STATE_COUNT ? s_state_names[state] : "invalid";
}

/* ---------------------------------------------------------------------------
 * Deep-sleep cycle counter
 *
 * Waking from deep sleep reboots the chip, so the machine needs state that
 * survives the reboot to tell "first pass" from "budget exhausted". RTC slow
 * memory survives deep sleep but not the power loss of S2, which is exactly
 * the lifetime needed here; the magic value rejects the undefined contents
 * seen right after a real power cycle. Whether the RTC memory actually holds
 * across deep sleep on S31 silicon still needs EVT confirmation - if it is
 * lost every time, the counter reads zero forever and the machine degrades
 * to looping S0..S1..deep sleep without ever reaching S2. It still cannot
 * wedge, because the RTC timer wake source fires either way.
 * ------------------------------------------------------------------------- */

/** Reboot-surviving record of the deep-sleep passes in this power session. */
typedef struct {
    uint32_t magic;     /**< DEEP_SLEEP_COUNT_MAGIC when cycles is valid. */
    uint32_t cycles;    /**< Deep-sleep entries so far. */
} deep_sleep_counter_t;

static RTC_NOINIT_ATTR deep_sleep_counter_t s_deep_sleep_counter;

/** Number of deep-sleep passes recorded for the current power session. */
static uint32_t deep_sleep_cycles_done(void)
{
    if (s_deep_sleep_counter.magic != DEEP_SLEEP_COUNT_MAGIC) {
        return 0;
    }
    return s_deep_sleep_counter.cycles;
}

/** Start a fresh power session: any non-deep-sleep boot invalidates RTC memory. */
static void deep_sleep_counter_reset(void)
{
    s_deep_sleep_counter.magic = DEEP_SLEEP_COUNT_MAGIC;
    s_deep_sleep_counter.cycles = 0;
}

/* ---------------------------------------------------------------------------
 * Shared IRQ pad ownership
 *
 * GPIO2 can be driven either by the LP core (RTC function, LP IO matrix) or by
 * the HP core (digital function), never both at once.
 *
 * The BSP configures the pin as a digital input inside bsp_shared_irq_service()
 * but only on the first call: shared_irq_gpio_init() is guarded by a one-shot
 * flag, so later service calls perform I2C work plus a gpio_get_level() and
 * leave the pin configuration alone. This example still re-asserts ownership
 * explicitly around every handover, both to survive that first call and to
 * keep the intent readable.
 *
 * Caveat for EVT: gpio_get_level() reads the digital input register, so its
 * value while the pad is muxed to the RTC function is not guaranteed to track
 * the real line. Servicing the line therefore happens with the pad on the HP
 * side, and ownership is handed back to the LP core afterwards.
 * ------------------------------------------------------------------------- */

/** Route GPIO2 to the LP core as a pulled-up RTC input. */
static esp_err_t claim_shared_irq_pad_for_lp(void)
{
    ESP_RETURN_ON_FALSE(rtc_gpio_is_valid_gpio(BSP_PMIC_RTC_INT),
                        ESP_ERR_NOT_SUPPORTED, TAG,
                        "GPIO%d is not an RTC pad", BSP_PMIC_RTC_INT);
    ESP_RETURN_ON_ERROR(rtc_gpio_init(BSP_PMIC_RTC_INT), TAG,
                        "shared IRQ RTC pad init failed");
    ESP_RETURN_ON_ERROR(rtc_gpio_set_direction(BSP_PMIC_RTC_INT,
                        RTC_GPIO_MODE_INPUT_ONLY), TAG,
                        "shared IRQ RTC direction failed");
    ESP_RETURN_ON_ERROR(rtc_gpio_pullup_en(BSP_PMIC_RTC_INT), TAG,
                        "shared IRQ pull-up failed");
    return ESP_OK;
}

/**
 * Drain the two I2C devices behind the shared line with the pad on the HP side.
 *
 * Servicing is HP-core work: it is I2C traffic plus a level check, and the
 * BSP's loop terminates on gpio_get_level(). That read is only trustworthy
 * while the pad is muxed to the digital function, so the RTC function is
 * released first and handed back to the LP housekeeper afterwards.
 */
static esp_err_t service_shared_irq(bsp_shared_irq_status_t *status)
{
    const bool hand_back = s_lp_running;
    if (hand_back) {
        /* Give the pad to the HP core for the duration of the service loop. */
        (void)rtc_gpio_deinit(BSP_PMIC_RTC_INT);
    }

    esp_err_t error = bsp_shared_irq_service(status);

    if (hand_back) {
        const esp_err_t restore = claim_shared_irq_pad_for_lp();
        if (restore != ESP_OK) {
            ESP_LOGE(TAG, "shared IRQ pad handback to LP core failed: %s",
                     esp_err_to_name(restore));
            if (error == ESP_OK) {
                error = restore;
            }
        }
    }
    return error;
}

/* ---------------------------------------------------------------------------
 * LP housekeeper glue
 * ------------------------------------------------------------------------- */

/** Mailbox receive callback. Runs in ISR context: only queue the message. */
static void lp_report_callback(lp_message_t msg)
{
    if (s_lp_reports == NULL) {
        return;
    }
    BaseType_t task_woken = pdFALSE;
    const int32_t value = (int32_t)msg;
    (void)xQueueSendFromISR(s_lp_reports, &value, &task_woken);
    if (task_woken != pdFALSE) {
        portYIELD_FROM_ISR();
    }
}

/**
 * Load and start the LP housekeeper, then attach the mailbox.
 *
 * GPIO2 is handed to the LP core here: rtc_gpio_init() must have been called
 * for the pad before the LP firmware runs, and the HP core must not arm its
 * own digital interrupt on GPIO2 until stop_lp_housekeeper() runs.
 */
static esp_err_t start_lp_housekeeper(void)
{
    if (s_lp_running) {
        return ESP_OK;
    }

    esp_err_t error = claim_shared_irq_pad_for_lp();
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "shared IRQ pad handover to LP core failed: %s",
                 esp_err_to_name(error));
        return error;
    }

    error = ulp_lp_core_load_binary(lp_core_main_bin_start,
                                    (size_t)(lp_core_main_bin_end -
                                             lp_core_main_bin_start));
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "LP core binary load failed: %s",
                 esp_err_to_name(error));
        goto fail_pad;
    }

    /* HP_CPU starts the core once; the LP firmware then loops on its own. */
    ulp_lp_core_cfg_t cfg = {
        .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_HP_CPU,
    };
    error = ulp_lp_core_run(&cfg);
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "LP core start failed: %s", esp_err_to_name(error));
        goto fail_pad;
    }
    s_lp_running = true;

    /* The software mailbox requires the LP core to call lp_core_mailbox_init()
     * before the HP core does; give its boot path time to get there. */
    vTaskDelay(pdMS_TO_TICKS(100));

    error = lp_core_mailbox_init(&s_mailbox, NULL);
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "LP mailbox init failed: %s", esp_err_to_name(error));
        goto fail_core;
    }

    /* Receive continuously. UINT32_MAX stands in for "until cancelled": the
     * count is decremented per message and cancel() ends it in S1/S2. */
    error = lp_core_mailbox_receive_async(s_mailbox, UINT32_MAX,
                                          lp_report_callback);
    if (error != ESP_OK) {
        ESP_LOGE(TAG, "LP mailbox async receive failed: %s",
                 esp_err_to_name(error));
        lp_core_mailbox_deinit(s_mailbox);
        s_mailbox = NULL;
        goto fail_core;
    }
    ESP_LOGI(TAG, "LP housekeeper running, GPIO%d owned by LP core",
             BSP_PMIC_RTC_INT);
    return ESP_OK;

fail_core:
    ulp_lp_core_stop();
    s_lp_running = false;
fail_pad:
    (void)rtc_gpio_deinit(BSP_PMIC_RTC_INT);
    return error;
}

/** Stop the LP housekeeper and return GPIO2 ownership to the HP core. */
static void stop_lp_housekeeper(void)
{
    if (!s_lp_running) {
        return;
    }
    uint32_t remaining = 0;
    if (s_mailbox != NULL) {
        (void)lp_core_mailbox_receive_async_cancel(s_mailbox, &remaining);
        lp_core_mailbox_deinit(s_mailbox);
        s_mailbox = NULL;
    }
    ulp_lp_core_stop();
    s_lp_running = false;

    /* Release the RTC function on GPIO2 so the HP core can drive it as an
     * ordinary digital input again. Without this the pad stays routed to the
     * LP IO matrix and the HP-side gpio_wakeup_enable() has no effect. */
    (void)rtc_gpio_deinit(BSP_PMIC_RTC_INT);
    ESP_LOGI(TAG, "LP housekeeper stopped, GPIO%d back on the HP core",
             BSP_PMIC_RTC_INT);
}

/** Drain and log everything the LP core reported so far. */
static void drain_lp_reports(void)
{
    int32_t msg = 0;
    while (s_lp_reports != NULL &&
            xQueueReceive(s_lp_reports, &msg, 0) == pdTRUE) {
        const uint8_t event = candis_lp_msg_event(msg);
        const uint32_t payload = candis_lp_msg_payload(msg);
        switch (event) {
        case CANDIS_LP_EVENT_BOOT:
            ESP_LOGI(TAG, "LP report: boot, protocol v%u", (unsigned)payload);
            break;
        case CANDIS_LP_EVENT_HEARTBEAT:
            ESP_LOGI(TAG, "LP report: heartbeat, poll #%u", (unsigned)payload);
            break;
        case CANDIS_LP_EVENT_IRQ_ASSERTED:
            ESP_LOGW(TAG, "LP report: shared IRQ asserted at poll #%u",
                     (unsigned)payload);
            /* The LP core only watches the line level; clearing the latched
             * flags behind it is an I2C job and belongs to the HP core.
             * service_shared_irq() gives the pad back to the LP core after
             * the drain. */
            {
                bsp_shared_irq_status_t status = {0};
                const esp_err_t error = service_shared_irq(&status);
                ESP_LOGI(TAG, "shared IRQ service: %s, pmic %02x %02x %02x, "
                         "rtc %02x, passes %u, released %d",
                         esp_err_to_name(error), status.pmic[0],
                         status.pmic[1], status.pmic[2], status.rtc,
                         status.service_passes, (int)status.line_released);
            }
            break;
        case CANDIS_LP_EVENT_IRQ_RELEASED:
            ESP_LOGI(TAG, "LP report: shared IRQ released at poll #%u",
                     (unsigned)payload);
            break;
        case CANDIS_LP_EVENT_I2C_SAMPLE:
            ESP_LOGI(TAG, "LP report: I2C sample 0x%02x",
                     (unsigned)(payload & 0xFFU));
            break;
        case CANDIS_LP_EVENT_I2C_ERROR:
            ESP_LOGW(TAG, "LP report: I2C error %u", (unsigned)payload);
            break;
        default:
            ESP_LOGW(TAG, "LP report: unknown event 0x%02x payload %u",
                     event, (unsigned)payload);
            break;
        }
    }
}

/* ---------------------------------------------------------------------------
 * Wake-source helpers
 * ------------------------------------------------------------------------- */

/** Log which sources woke the HP core from the last light sleep. */
static void log_wakeup_causes(void)
{
    const uint32_t causes = esp_sleep_get_wakeup_causes();
    ESP_LOGI(TAG, "wake causes 0x%08x%s%s%s%s", (unsigned)causes,
             (causes & BIT(ESP_SLEEP_WAKEUP_TIMER)) ? " timer" : "",
             (causes & BIT(ESP_SLEEP_WAKEUP_GPIO)) ? " gpio" : "",
             (causes & BIT(ESP_SLEEP_WAKEUP_ULP)) ? " ulp" : "",
             (causes & BIT(ESP_SLEEP_WAKEUP_UNDEFINED)) ? " undefined" : "");
}

/**
 * Arm light-sleep wake sources for S1.
 *
 * gpio_wakeup_enable() plus esp_sleep_enable_gpio_wakeup() is the light-sleep
 * path that works on any pad. The shared line and the optional touch line are
 * active low and externally pulled up, so present sources use level low.
 */
static esp_err_t arm_light_sleep_sources(bool include_shared_irq)
{
    if (s_touch != NULL) {
        ESP_RETURN_ON_ERROR(gpio_wakeup_enable(BSP_TOUCH_INT,
                            GPIO_INTR_LOW_LEVEL), TAG,
                            "touch INT wake-up arm failed");
    }
    if (include_shared_irq) {
        /* Only valid while the LP core is stopped: otherwise the pad belongs
         * to the LP core and this HP-side configuration fights it.
         * The pad is (re)configured as a digital input here because
         * stop_lp_housekeeper() released the RTC function and nothing else
         * guarantees a digital input configuration at this point. */
        const gpio_config_t shared_irq_input = {
            .pin_bit_mask = BIT64(BSP_PMIC_RTC_INT),
            .mode = GPIO_MODE_INPUT,
            .pull_up_en = GPIO_PULLUP_ENABLE,
            .pull_down_en = GPIO_PULLDOWN_DISABLE,
            .intr_type = GPIO_INTR_DISABLE,
        };
        ESP_RETURN_ON_ERROR(gpio_config(&shared_irq_input), TAG,
                            "shared IRQ input config failed");
        ESP_RETURN_ON_ERROR(gpio_wakeup_enable(BSP_PMIC_RTC_INT,
                                               GPIO_INTR_LOW_LEVEL),
                            TAG, "shared IRQ wake-up arm failed");
    }
    ESP_RETURN_ON_ERROR(esp_sleep_enable_gpio_wakeup(), TAG,
                        "GPIO wake-up source enable failed");
    return ESP_OK;
}

/** Release the wake sources armed by arm_light_sleep_sources(). */
static void disarm_light_sleep_sources(bool include_shared_irq)
{
    if (s_touch != NULL) {
        (void)gpio_wakeup_disable(BSP_TOUCH_INT);
    }
    if (include_shared_irq) {
        (void)gpio_wakeup_disable(BSP_PMIC_RTC_INT);
    }
    (void)esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_GPIO);
}

/* ---------------------------------------------------------------------------
 * Display and touch
 * ------------------------------------------------------------------------- */

/**
 * Bring up the CO5300 panel and the CST820 controller.
 *
 * bsp_display_new() is used instead of bsp_display_start(): the prototype has
 * no UI, and this keeps LVGL out of the runtime path while still giving
 * bsp_display_enter_sleep()/exit_sleep() the panel handle they require.
 */
static esp_err_t display_and_touch_start(void)
{
    if (s_display_ready) {
        return ESP_OK;
    }
    const bsp_display_config_t config = {
        .max_transfer_sz = BSP_LCD_H_RES * 80 * (int)sizeof(uint16_t),
    };
    ESP_RETURN_ON_ERROR(bsp_display_new(&config, &s_panel, &s_panel_io), TAG,
                        "CO5300 bring-up failed");
    s_display_ready = true;
    s_display_asleep = false;

    /* Touch is optional during EVT: a loose FPC must not stop the state
     * machine, it only removes the touch wake source. */
    if (bsp_touch_new(NULL, &s_touch) != ESP_OK) {
        s_touch = NULL;
        ESP_LOGW(TAG, "CST820 bring-up failed, continuing without touch wake");
    }
    return ESP_OK;
}

/**
 * Put panel and touch into their S1 low-power modes.
 *
 * bsp_display_enter_sleep() also drives the touch controller into its deep
 * sleep (~2 uA) through esp_lcd_touch_enter_sleep(), and that mode cannot be
 * woken by a touch. Monitor mode is therefore restored afterwards with a reset
 * cycle: esp_lcd_touch_cst820_wakeup() brings the controller back to dynamic
 * mode, and enter_monitor_mode() lets it fall into touch-wakeable standby.
 */
static esp_err_t display_and_touch_sleep(void)
{
    ESP_RETURN_ON_FALSE(s_display_ready, ESP_ERR_INVALID_STATE, TAG,
                        "display is not initialized");
    ESP_RETURN_ON_ERROR(bsp_display_enter_sleep(), TAG,
                        "CO5300 sleep-in failed");
    s_display_asleep = true;

    if (s_touch != NULL) {
        const esp_err_t wake_error = esp_lcd_touch_cst820_wakeup(s_touch);
        if (wake_error != ESP_OK) {
            ESP_LOGW(TAG, "CST820 reset out of deep sleep failed: %s",
                     esp_err_to_name(wake_error));
        }
        const esp_err_t monitor_error =
            esp_lcd_touch_cst820_enter_monitor_mode(s_touch);
        if (monitor_error != ESP_OK) {
            ESP_LOGW(TAG, "CST820 monitor mode failed: %s",
                     esp_err_to_name(monitor_error));
        }
    }
    return ESP_OK;
}

/** Restore panel and touch after S1. */
static esp_err_t display_and_touch_resume(void)
{
    ESP_RETURN_ON_FALSE(s_display_ready, ESP_ERR_INVALID_STATE, TAG,
                        "display is not initialized");
    if (s_touch != NULL) {
        /* Reset path back to dynamic mode; the controller would also leave
         * standby on its own at the next touch. */
        const esp_err_t error = esp_lcd_touch_cst820_exit_monitor_mode(s_touch);
        if (error != ESP_OK) {
            ESP_LOGW(TAG, "CST820 monitor exit failed: %s",
                     esp_err_to_name(error));
        }
    }
    if (s_display_asleep) {
        ESP_RETURN_ON_ERROR(bsp_display_exit_sleep(), TAG,
                            "CO5300 sleep-out failed");
        s_display_asleep = false;
    }
    return ESP_OK;
}

/* ---------------------------------------------------------------------------
 * RTC alarm for S2
 * ------------------------------------------------------------------------- */

static uint8_t days_in_month(uint16_t year, uint8_t month)
{
    static const uint8_t lengths[12] = {
        31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
    };
    if (month < 1 || month > 12) {
        return 31;
    }
    if (month == 2 &&
            ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0)) {
        return 29;
    }
    return lengths[month - 1];
}

/** Advance a calendar value by whole minutes, carrying into the month. */
static void time_add_minutes(rx8130ce_time_t *time, uint16_t minutes)
{
    uint32_t total = (uint32_t)time->minute + minutes;
    time->minute = (uint8_t)(total % 60U);
    uint32_t hours = (uint32_t)time->hour + total / 60U;
    time->hour = (uint8_t)(hours % 24U);
    uint32_t days = hours / 24U;
    while (days-- > 0) {
        const uint8_t length = days_in_month(time->year, time->month);
        if (time->day < length) {
            time->day++;
        } else {
            time->day = 1;
            if (time->month == 12) {
                time->month = 1;
                time->year++;
            } else {
                time->month++;
            }
        }
        time->weekday = (uint8_t)((time->weekday + 1U) % 7U);
    }
}

/**
 * Arm the RX8130CE alarm S2_ALARM_MINUTES from now.
 *
 * The board carries no 32.768 kHz crystal, so the RTC alarm is the only
 * hardware timed path that survives the main rail going down. Sequence
 * follows the shared-IRQ contract: set the alarm, gate it onto /IRQ, clear
 * any latched flag, then confirm the shared line is released before sleeping.
 */
static esp_err_t arm_rtc_wakeup_alarm(void)
{
    bsp_rtc_time_t bsp_now = {0};
    bsp_rtc_status_t status = {0};
    ESP_RETURN_ON_ERROR(bsp_rtc_get_time(&bsp_now, &status), TAG,
                        "RTC time read failed");
    if (!status.time_valid) {
        /* VLF=1: the backup domain dropped out, so the calendar and the alarm
         * registers are meaningless. Refusing to continue is safer than
         * cutting the main rail with an alarm that will never fire. */
        ESP_LOGE(TAG, "RTC reports invalid time (VLF set); refusing to arm");
        return ESP_ERR_INVALID_STATE;
    }

    /* bsp_rtc_time_t and rx8130ce_time_t are distinct but field-identical;
     * rx8130ce_alarm_from_time() is a pure helper on the driver type. */
    const rx8130ce_time_t now = {
        .year = bsp_now.year,
        .month = bsp_now.month,
        .day = bsp_now.day,
        .weekday = bsp_now.weekday,
        .hour = bsp_now.hour,
        .minute = bsp_now.minute,
        .second = bsp_now.second,
    };
    rx8130ce_time_t target = now;
    time_add_minutes(&target, S2_ALARM_MINUTES);

    bsp_rtc_alarm_t alarm = {0};
    ESP_RETURN_ON_ERROR(rx8130ce_alarm_from_time(&now, &target, &alarm), TAG,
                        "alarm conversion failed");
    ESP_RETURN_ON_ERROR(bsp_rtc_set_alarm(&alarm), TAG, "alarm write failed");
    ESP_RETURN_ON_ERROR(bsp_rtc_alarm_irq_enable(true), TAG,
                        "alarm IRQ enable failed");

    /* Clear only AF before draining the wire-ANDed line. UF/TF remain
     * available to their consumers unless they are themselves holding the
     * shared line low, in which case service_shared_irq() reports and clears
     * them while making the shutdown wake path safe. */
    ESP_RETURN_ON_ERROR(bsp_rtc_get_and_clear_alarm_flag(NULL), TAG,
                        "alarm flag clear failed");
    bsp_shared_irq_status_t irq_status = {0};
    ESP_RETURN_ON_ERROR(service_shared_irq(&irq_status), TAG,
                        "shared IRQ line drain before shutdown failed");
    ESP_RETURN_ON_FALSE(irq_status.line_released, ESP_ERR_TIMEOUT, TAG,
                        "shared IRQ line remained asserted before shutdown");

    ESP_LOGI(TAG, "RTC alarm armed for %04u-%02u-%02u %02u:%02u "
             "(now %02u:%02u:%02u, +%d min)",
             (unsigned)target.year, (unsigned)target.month,
             (unsigned)target.day, (unsigned)target.hour,
             (unsigned)target.minute, (unsigned)now.hour,
             (unsigned)now.minute, (unsigned)now.second,
             S2_ALARM_MINUTES);
    return ESP_OK;
}

/* ---------------------------------------------------------------------------
 * State entry actions
 * ------------------------------------------------------------------------- */

/** Enter S0: panel on, LP housekeeper delegated the shared-IRQ watch. */
static esp_err_t enter_run(void)
{
    ESP_RETURN_ON_ERROR(display_and_touch_start(), TAG,
                        "display bring-up failed");
    ESP_RETURN_ON_ERROR(display_and_touch_resume(), TAG,
                        "display resume failed");
    ESP_RETURN_ON_ERROR(start_lp_housekeeper(), TAG,
                        "LP housekeeper start failed");

    /* The LP core owns GPIO2, so the HP core does not arm it. It still needs
     * a wake path for the mailbox notification: that is the ULP source. */
    ESP_RETURN_ON_ERROR(esp_sleep_enable_ulp_wakeup(), TAG,
                        "ULP wake-up enable failed");
    return ESP_OK;
}

/**
 * Run S0 for its dwell time.
 *
 * This is the delegation demo: instead of polling the RTC and PMIC itself, the
 * HP core light-sleeps in slices and only wakes when the LP core reports, or
 * when the slice timer expires.
 */
static void run_state_run(void)
{
    const int slices = (S0_DWELL_SECONDS * 1000000) / (int)S0_SLEEP_SLICE_US;
    for (int slice = 0; slice < slices; ++slice) {
        if (esp_sleep_enable_timer_wakeup(S0_SLEEP_SLICE_US) != ESP_OK) {
            ESP_LOGE(TAG, "timer wake-up arm failed, staying awake");
            vTaskDelay(pdMS_TO_TICKS(S0_SLEEP_SLICE_US / 1000));
        } else if (esp_light_sleep_start() != ESP_OK) {
            ESP_LOGW(TAG, "light sleep rejected in S0");
            vTaskDelay(pdMS_TO_TICKS(100));
        } else {
            log_wakeup_causes();
        }
        drain_lp_reports();
    }
    (void)esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER);
}

/**
 * Enter S1: panel and touch to low power, LP core stopped, HP light-sleeping.
 *
 * The LP core is stopped so the HP core can own GPIO2 and take the shared IRQ
 * line directly as a level-low wake source, which is what the state
 * definition calls for. Keeping the LP core running instead would mean waking
 * through the ULP source; the two cannot both drive the pad.
 */
static esp_err_t enter_screen_off(void)
{
    ESP_RETURN_ON_ERROR(display_and_touch_sleep(), TAG,
                        "display sleep failed");
    stop_lp_housekeeper();
    (void)esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_ULP);
    ESP_RETURN_ON_ERROR(arm_light_sleep_sources(true), TAG,
                        "S1 wake-up sources failed");
    return ESP_OK;
}

/**
 * Light-sleep in S1 until a wake source fires or the escalation budget ends.
 *
 * @return true when the user asked to come back (touch), false when the budget
 *         ran out and the machine should drop into deep sleep. The result is
 *         returned explicitly instead of re-reading esp_sleep_get_wakeup_causes()
 *         afterwards: a shared-IRQ wake also sets the GPIO cause bit, so the
 *         cause bitmap alone cannot tell "user touched" from "PMIC/RTC event".
 */
static bool run_state_screen_off(void)
{
    bool user_requested_wake = false;
    for (int slice = 0; slice < S1_SLICES_BEFORE_S2; ++slice) {
        if (esp_sleep_enable_timer_wakeup(S1_SLEEP_SLICE_US) != ESP_OK) {
            ESP_LOGE(TAG, "timer wake-up arm failed in S1");
            break;
        }
        if (esp_light_sleep_start() != ESP_OK) {
            ESP_LOGW(TAG, "light sleep rejected in S1");
            vTaskDelay(pdMS_TO_TICKS(100));
            continue;
        }
        const uint32_t causes = esp_sleep_get_wakeup_causes();
        log_wakeup_causes();

        if (causes & BIT(ESP_SLEEP_WAKEUP_GPIO)) {
            /* Either the panel was touched or one of the I2C devices behind
             * the shared line asserted. Reading the levels tells them apart:
             * both lines are active low. */
            const bool shared_low =
                gpio_get_level(BSP_PMIC_RTC_INT) == BSP_PMIC_RTC_INT_ACTIVE_LEVEL;
            const bool touch_low = s_touch != NULL &&
                                   gpio_get_level(BSP_TOUCH_INT) == 0;
            ESP_LOGI(TAG, "S1 GPIO wake: shared_irq=%d touch=%d",
                     (int)shared_low, (int)touch_low);
            if (shared_low) {
                /* The LP core is stopped in S1, so service_shared_irq() only
                 * forwards to the BSP here; it is used for consistency. */
                bsp_shared_irq_status_t status = {0};
                const esp_err_t error = service_shared_irq(&status);
                ESP_LOGI(TAG, "shared IRQ service: %s, pmic %02x %02x %02x, "
                         "rtc %02x, released %d",
                         esp_err_to_name(error),
                         status.pmic[0], status.pmic[1], status.pmic[2],
                         status.rtc, (int)status.line_released);
                /* TG28 power-key IRQs live in bank 1 bits 0-3
                 * (PONPE/PONNE/PONLP/PONSP, see tg28_sw.h). Treat a
                 * short or long press as a user request to wake — the
                 * power key is the natural wake gesture while the screen
                 * is off. */
                if (error == ESP_OK && (status.pmic[1] & 0x0F) != 0) {
                    ESP_LOGI(TAG, "power key detected on shared IRQ, waking to S0");
                    user_requested_wake = true;
                    break;
                }
            }
            if (touch_low) {
                /* A touch is a user request to come back: leave S1. */
                user_requested_wake = true;
                break;
            }
        }
    }
    (void)esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_TIMER);
    return user_requested_wake;
}

/** Leave S1 and release the wake sources it owns. */
static void exit_screen_off(void)
{
    disarm_light_sleep_sources(true);
}

/** Release protocol owners while their supplies are still present.
 *
 * Boot failure, deep sleep, and S2 all use this idempotent helper before the
 * BSP parks pins or removes rails.
 */
static esp_err_t stop_active_peripheral_owners(void)
{
    esp_err_t first_error = ESP_OK;
    if (s_touch != NULL) {
        first_error = bsp_touch_delete();
    }
    if (s_display_ready) {
        bsp_display_delete();
    }
    s_display_ready = false;
    s_display_asleep = false;
    s_touch = NULL;
    s_panel = NULL;
    s_panel_io = NULL;
    return first_error;
}

static esp_err_t low_power_safe_state(void)
{
    const esp_err_t owner_error = stop_active_peripheral_owners();
    const esp_err_t rail_error = bsp_power_safe_state();
    return owner_error != ESP_OK ? owner_error : rail_error;
}

/**
 * Enter deep sleep, the step between S1 and S2.
 *
 * The panel/touch protocol owners and every optional rail are shut down before
 * entry. On wake the ESP reboots and bsp_board_init() applies the same safe
 * state again, so S0 reinitializes peripherals rather than relying on their
 * state to survive. The always-on RX8130CE/TG28 behind the shared IRQ line do
 * not depend on an optional peripheral rail.
 *
 * Wake sources are the SoC RTC timer and EXT1 (any low) on the shared IRQ
 * line. Only PMIC/RTC events can assert that line: the CST820 touch INT is
 * GPIO3 and is NOT wired to GPIO2, so a touch cannot wake deep sleep in
 * this configuration. Waking from deep sleep reboots the chip, so this
 * function does not return on success; app_main reads the cycle counter
 * from RTC memory on the next boot and routes the machine back to S0 or on
 * to S2.
 */
static esp_err_t enter_deep_sleep(void)
{
    /* Idempotent: S1 already stopped the housekeeper, but this guarantees
     * GPIO2 is back on the HP side however the machine got here. */
    stop_lp_housekeeper();

    /* The S1 light-sleep sources use the digital pad function; EXT1 needs the
     * RTC function instead, so they must go before the pad is re-muxed. */
    disarm_light_sleep_sources(true);

    /* Deep sleep must not preserve optional rails. Release active protocol
     * owners, then park pins and remove every peripheral/control supply. */
    const esp_err_t safe_error = low_power_safe_state();
    if (safe_error != ESP_OK) {
        ESP_LOGE(TAG, "pre-deep-sleep safe-state failed: %s",
                 esp_err_to_name(safe_error));
        return safe_error;
    }

    const esp_err_t timer_error =
        esp_sleep_enable_timer_wakeup(DEEP_SLEEP_WAKE_US);
    if (timer_error != ESP_OK) {
        ESP_LOGE(TAG, "deep-sleep timer wake-up arm failed: %s",
                 esp_err_to_name(timer_error));
    }

    /* EXT1 on the shared IRQ line. GPIO2 is pulled up through R10; enable the
     * internal pull-up as well so the pad keeps a defined level even without
     * the external resistor. A floating EXT1 pin is exactly what keeps the
     * chip in deep sleep forever. Only TG28/RX8130CE events assert this line;
     * touch (GPIO3) is deliberately not armed - see the function comment. */
    esp_err_t ext1_error = rtc_gpio_init(BSP_PMIC_RTC_INT);
    if (ext1_error == ESP_OK) {
        ext1_error = rtc_gpio_set_direction(BSP_PMIC_RTC_INT,
                                            RTC_GPIO_MODE_INPUT_ONLY);
    }
    if (ext1_error == ESP_OK) {
        ext1_error = rtc_gpio_pullup_en(BSP_PMIC_RTC_INT);
    }
    if (ext1_error == ESP_OK) {
        ext1_error = esp_sleep_enable_ext1_wakeup_io(BIT(BSP_PMIC_RTC_INT),
                                                     ESP_EXT1_WAKEUP_ANY_LOW);
    }
    if (ext1_error != ESP_OK) {
        ESP_LOGE(TAG, "deep-sleep EXT1 wake-up arm failed: %s",
                 esp_err_to_name(ext1_error));
    }

    if (timer_error != ESP_OK && ext1_error != ESP_OK) {
        /* With no wake source armed, deep sleep would be permanent. Refuse it
         * so the state machine escalates to S2 instead. */
        return ESP_ERR_INVALID_STATE;
    }

    s_deep_sleep_counter.magic = DEEP_SLEEP_COUNT_MAGIC;
    s_deep_sleep_counter.cycles++;

    ESP_LOGW(TAG, "deep sleep: cycle %u/%u, wake on RTC timer (%u s) or "
             "GPIO%d low (EXT1)",
             (unsigned)s_deep_sleep_counter.cycles,
             (unsigned)DEEP_SLEEP_MAX_CYCLES,
             (unsigned)(DEEP_SLEEP_WAKE_US / 1000000ULL),
             BSP_PMIC_RTC_INT);
    vTaskDelay(pdMS_TO_TICKS(50));   /* let the log drain */
    esp_deep_sleep_start();

    /* Not reached: waking from deep sleep reboots the chip. */
    return ESP_OK;
}

/**
 * Enter S2: shed the peripheral rails, arm the RTC alarm, then ask the PMIC
 * for a software power-off so the board loses power.
 *
 * Order matters. Peripherals go first so nothing is back-fed while its supply
 * collapses, the alarm is armed while I2C is still alive, and DCDC1 is last
 * because the ESP dies with it.
 */
static esp_err_t enter_shutdown(void)
{
    stop_lp_housekeeper();
    disarm_light_sleep_sources(true);

    const esp_err_t safe_error = low_power_safe_state();
    if (safe_error != ESP_OK) {
        ESP_LOGE(TAG, "board safe-state failed: %s",
                 esp_err_to_name(safe_error));
        /* Do not cut the main rail after incomplete owner/rail teardown:
         * remain powered with the failure visible for diagnosis. */
        return safe_error;
    }

    /* VBUS guard: when USB power is present the TG28 REG10 bit0 soft-power-off
     * may reboot the board instead of cutting power (bring-up.md documents this
     * against the Linux reference implementation). Without this guard the
     * machine would loop: S2 → reboot → cold boot (counter reset) → S0 → S1 →
     * deep sleep → S2 → reboot … never actually turning off. Refuse the
     * power-off so the caller can idle with the rails safely down. The alarm
     * is still armed so the board wakes on schedule once USB is removed. */
    bsp_pmic_status_t pmic_status = {0};
    if (bsp_pmic_get_status(&pmic_status) == ESP_OK && pmic_status.vbus_present) {
        ESP_LOGW(TAG, "VBUS present: deferring PMIC power-off to avoid reboot "
                 "loop; the board stays powered with all peripheral rails off. "
                 "Remove USB to complete shutdown or reset to restart.");
        return ESP_ERR_INVALID_STATE;
    }

    ESP_RETURN_ON_ERROR(arm_rtc_wakeup_alarm(), TAG,
                        "RTC wake-up alarm failed");

    ESP_LOGW(TAG, "requesting PMIC power-off: the board loses power now");
    vTaskDelay(pdMS_TO_TICKS(50));   /* let the log drain */
    const esp_err_t power_off = bsp_pmic_power_off();
    /* Reached only when the PMIC refused: a successful software power-off
     * drops DCDC1 and the ESP dies before this statement executes. */
    ESP_LOGE(TAG, "bsp_pmic_power_off() returned %s - still powered",
             esp_err_to_name(power_off));
    return power_off == ESP_OK ? ESP_ERR_INVALID_STATE : power_off;
}

/* ---------------------------------------------------------------------------
 * Board bring-up and state machine
 * ------------------------------------------------------------------------- */

/**
 * Report why this boot happened.
 *
 * After S2 the ESP was unpowered, so a return from S2 is a cold boot and the
 * wake cause reads as undefined. The PMIC power-on source and the RTC alarm
 * flag are what actually identify an alarm-driven restart, which is why the
 * shared line is drained here before anything else touches it.
 */
static esp_err_t report_boot_reason(void)
{
    log_wakeup_causes();

    uint8_t power_on_source = 0;
    if (bsp_pmic_get_power_on_source(&power_on_source) == ESP_OK) {
        ESP_LOGI(TAG, "PMIC power-on source 0x%02x", power_on_source);
    }

    bsp_rtc_status_t rtc_status = {0};
    if (bsp_rtc_get_status(&rtc_status) == ESP_OK) {
        ESP_LOGI(TAG, "RTC flags 0x%02x: time_valid=%d alarm=%d timer=%d "
                 "backup_low=%d", rtc_status.raw, (int)rtc_status.time_valid,
                 (int)rtc_status.alarm, (int)rtc_status.timer,
                 (int)rtc_status.backup_voltage_low);
    }

    /* Contract D3: drain the shared line once at start-up whatever the wake
     * reason was, so a latched AF cannot hold GPIO2 low into the application. */
    bsp_shared_irq_status_t irq_status = {0};
    const esp_err_t error = service_shared_irq(&irq_status);
    ESP_LOGI(TAG, "start-up shared IRQ drain: %s, pmic %02x %02x %02x, "
             "rtc %02x, passes %u, released %d", esp_err_to_name(error),
             irq_status.pmic[0], irq_status.pmic[1], irq_status.pmic[2],
             irq_status.rtc, irq_status.service_passes,
             (int)irq_status.line_released);
    return error;
}

static esp_err_t board_bring_up(void)
{
    ESP_RETURN_ON_ERROR(bsp_board_init(), TAG, "board init failed");
    ESP_RETURN_ON_ERROR(bsp_lp_i2c_init(), TAG, "low-power I2C init failed");
    ESP_RETURN_ON_ERROR(bsp_pmic_init(), TAG, "TG28 init failed");
    ESP_RETURN_ON_ERROR(bsp_rtc_init(), TAG, "RX8130CE init failed");

    /* The shared IRQ pad is claimed and released around the LP core lifetime
     * (see start_lp_housekeeper() / stop_lp_housekeeper()) rather than being
     * configured once here, so only the capability is checked at bring-up. */
    if (!rtc_gpio_is_valid_gpio(BSP_PMIC_RTC_INT)) {
        ESP_LOGW(TAG, "GPIO%d is not an RTC pad; the LP housekeeper cannot "
                 "watch the shared IRQ line", BSP_PMIC_RTC_INT);
    }
    return ESP_OK;
}

void app_main(void)
{
    ESP_LOGI(TAG, "%s low-power prototype, board %s",
             BSP_BOARD_NAME, BSP_BOARD_REVISION);

    s_lp_reports = xQueueCreate(LP_REPORT_QUEUE_DEPTH, sizeof(int32_t));
    if (s_lp_reports == NULL) {
        ESP_LOGE(TAG, "LP report queue allocation failed");
        return;
    }

    if (board_bring_up() != ESP_OK) {
        ESP_LOGE(TAG, "board bring-up failed; re-applying safe state");
        (void)low_power_safe_state();
        return;
    }
    if (report_boot_reason() != ESP_OK) {
        ESP_LOGE(TAG, "start-up shared IRQ could not be drained; stopping");
        (void)low_power_safe_state();
        return;
    }

    /* Route the boot. Waking from deep sleep reboots the chip with a real
     * wake cause (timer, EXT1, ...); every other boot - power-on, reset, or
     * the cold start after S2 cut the power - reports UNDEFINED and starts a
     * fresh cycle with the counter zeroed. For a deep-sleep wake the counter
     * in RTC memory decides between another S0 pass and the escalation to S2.
     * This does not disturb report_boot_reason(): an S2 restart still shows
     * up as UNDEFINED there, because the ESP was unpowered, not deep-sleeping. */
    /* Route the boot. Waking from deep sleep reboots the chip with a real
     * wake cause (timer, EXT1, ...); every other boot - power-on, reset, or
     * the cold start after S2 cut the power - reports UNDEFINED and starts a
     * fresh cycle with the counter zeroed.
     *
     * Within a deep-sleep wake, the source matters:
     * - EXT1 on GPIO2 means an external event (power key, RTC alarm) — the
     *   user or an alarm explicitly wants the board, so reset the counter
     *   and return to S0 regardless of how many idle cycles elapsed.
     * - TIMER means idle timeout — honour the escalation budget: another S0
     *   pass if the counter is within budget, S2 otherwise.
     * Both sources can fire simultaneously; EXT1 takes precedence so a
     * coincident timer expiry never sends a user wake to S2. */
    candis_state_t state;
    const uint32_t wake_causes = esp_sleep_get_wakeup_causes();
    if (wake_causes & BIT(ESP_SLEEP_WAKEUP_UNDEFINED)) {
        deep_sleep_counter_reset();
        state = CANDIS_STATE_RUN;
    } else if (wake_causes & BIT(ESP_SLEEP_WAKEUP_EXT1)) {
        ESP_LOGI(TAG, "woke from deep sleep by EXT1 (external event: "
                 "power key or RTC alarm), resetting counter and returning to S0");
        deep_sleep_counter_reset();
        state = CANDIS_STATE_RUN;
    } else if (deep_sleep_cycles_done() >= DEEP_SLEEP_MAX_CYCLES) {
        ESP_LOGI(TAG, "deep-sleep budget exhausted (%u cycles), going to S2",
                 (unsigned)deep_sleep_cycles_done());
        state = CANDIS_STATE_SHUTDOWN;
    } else {
        ESP_LOGI(TAG, "woke from deep sleep by timer, cycle %u/%u, returning to S0",
                 (unsigned)deep_sleep_cycles_done(),
                 (unsigned)DEEP_SLEEP_MAX_CYCLES);
        state = CANDIS_STATE_RUN;
    }

    while (1) {
        ESP_LOGI(TAG, "==> entering %s", state_name(state));
        switch (state) {
        case CANDIS_STATE_RUN:
            if (enter_run() != ESP_OK) {
                ESP_LOGE(TAG, "S0 entry failed");
                vTaskDelay(pdMS_TO_TICKS(2000));
                break;
            }
            run_state_run();
            state = CANDIS_STATE_SCREEN_OFF;
            break;

        case CANDIS_STATE_SCREEN_OFF:
            if (enter_screen_off() != ESP_OK) {
                ESP_LOGE(TAG, "S1 entry failed, returning to S0");
                exit_screen_off();
                state = CANDIS_STATE_RUN;
                break;
            }
            {
                const bool user_wake = run_state_screen_off();
                exit_screen_off();
                /* A touch returns to S0; exhausting the budget drops the
                 * machine into deep sleep first. */
                state = user_wake ? CANDIS_STATE_RUN : CANDIS_STATE_DEEP_SLEEP;
            }
            break;

        case CANDIS_STATE_DEEP_SLEEP:
            if (enter_deep_sleep() != ESP_OK) {
                /* No wake source could be armed: deep sleep would be
                 * permanent. Escalate to S2 instead. */
                ESP_LOGE(TAG, "deep-sleep entry failed, escalating to S2");
                state = CANDIS_STATE_SHUTDOWN;
                break;
            }
            /* Not reached: waking from deep sleep reboots the chip. */
            state = CANDIS_STATE_RUN;
            break;

        case CANDIS_STATE_SHUTDOWN:
            if (enter_shutdown() != ESP_OK) {
                ESP_LOGE(TAG, "S2 entry failed");
            }
            /* Reached only when the PMIC power-off was refused. Idle instead
             * of looping back: the peripheral rails are down and re-running
             * S0 would need a full re-initialization. */
            ESP_LOGW(TAG, "still powered after S2; idling. Reset the board or "
                     "cycle power to restart the state machine.");
            while (1) {
                vTaskDelay(pdMS_TO_TICKS(10000));
            }
            break;

        default:
            state = CANDIS_STATE_RUN;
            break;
        }
    }
}
