#!/usr/bin/env bash
set -euo pipefail

TOOLS_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$TOOLS_DIR/../.." && pwd)
DEMO_DIR="$REPO_ROOT/firmware/demo"
FONT_SOURCE="$DEMO_DIR/managed_components/lvgl__lvgl/scripts/built_in_font/SourceHanSansSC-Normal.otf"
FONT_OUTPUT="$DEMO_DIR/main/ui/fonts"
EXPECTED_SOURCE_SHA256="1ee89e1669362dee13851129c0a8a791a87521eb4148e5efbf5d26596738e25b"

actual_sha256=$(sha256sum "$FONT_SOURCE" | awk '{print $1}')
if [[ "$actual_sha256" != "$EXPECTED_SOURCE_SHA256" ]]; then
    echo "Source font checksum mismatch: $actual_sha256" >&2
    exit 1
fi

mkdir -p "$FONT_OUTPUT"

generate_font() {
    local size=$1
    local chars_file=$2
    local output=$3
    local symbols
    symbols=$(tr -d '\r\n' < "$chars_file")
    "$TOOLS_DIR/node_modules/.bin/lv_font_conv" \
        --no-compress --no-prefilter --bpp 4 --size "$size" \
        --font "$FONT_SOURCE" -r 0x20-0x7E --symbols "$symbols" \
        --format lvgl --lv-include lvgl.h --force-fast-kern-format \
        -o "$output"
    sed -i \
        's/\.fallback = NULL/\.fallback = \&lv_font_source_han_sans_sc_16_cjk/' \
        "$output"
    sed -i \
        '/^ \* Opts:/c\ * Generated by tools/fonts/generate.sh; see the pinned manifest there.' \
        "$output"
}

generate_font 20 "$TOOLS_DIR/chars-ui-20.txt" \
    "$FONT_OUTPUT/candis_ui_20.c"
generate_font 24 "$TOOLS_DIR/chars-ui-24.txt" \
    "$FONT_OUTPUT/candis_ui_24.c"

sha256sum "$FONT_OUTPUT/candis_ui_20.c" "$FONT_OUTPUT/candis_ui_24.c"

# Gate: every non-ASCII char used in demo UI strings must exist in the
# generated subsets or the built-in fallback. Fails the run otherwise.
bash "$TOOLS_DIR/check-coverage.sh"
